/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

use crate::{
    edit_index::{Index, js_space, starts},
    failed,
    mutation::MAX_CONTENT,
};
use maka_runtime::tools::ToolError;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::ops::Range;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EditMatchStrategy {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "line-trimmed")]
    LineTrimmed,
    #[serde(rename = "whitespace")]
    Whitespace,
    #[serde(rename = "escape")]
    Escape,
}

fn lines(s: &str) -> usize {
    1 + s.bytes().filter(|b| *b == b'\n').count()
}
fn trimmed_len(s: &str) -> usize {
    s.trim_matches(js_space).encode_utf16().count()
}

pub(crate) fn replace(
    source: &str,
    old: &str,
    new: &str,
    path: &str,
) -> Result<(String, Value), ToolError> {
    if old.is_empty() || old == new {
        return Err(failed("Edit requires nonempty, different old_string"));
    }
    let mut exact = source.match_indices(old);
    let found = exact.next();
    if exact.next().is_some() {
        return Err(failed("Edit exact match is not unique"));
    }
    let (span, strategy) = if let Some((offset, _)) = found {
        (offset..offset + old.len(), EditMatchStrategy::Exact)
    } else {
        if trimmed_len(old) < 5 {
            return Err(failed("Edit old_string is too short for a non-exact match"));
        }
        if source.contains('\0') {
            return Err(failed("Edit refuses non-exact match in binary text"));
        }
        if source.encode_utf16().count() > 1_000_000 || lines(source) > 50_000 {
            return Err(failed("Edit source is too large to fuzzy-match safely"));
        }
        fuzzy(source, old)?
    };
    let length = source.len() - span.len() + new.len();
    if length > MAX_CONTENT {
        return Err(failed("Edit output exceeds 1 MiB"));
    }
    let mut content = String::with_capacity(length);
    content.push_str(&source[..span.start]);
    content.push_str(new);
    content.push_str(&source[span.end..]);
    let start = lines(&source[..span.start]);
    let matched = &source[span];
    let end = start + lines(matched) - usize::from(matched.ends_with('\n')) - 1;
    Ok((
        content,
        json!({"ok":true,"path":path,"replacements":1,"matchedVia":strategy,"startLine":start,"endLine":end}),
    ))
}

// Full-span candidates are generated by indexed equality, never anchors or
// hashes. Each stage scans once. Candidate uniqueness needs only two full-file
// searches: any repeated candidate is already fatal, including overlapping ones.
fn fuzzy(source: &str, old: &str) -> Result<(Range<usize>, EditMatchStrategy), ToolError> {
    let text_lines: Vec<_> = source.split('\n').collect();
    let mut offsets = Vec::with_capacity(text_lines.len());
    let mut offset = 0;
    for line in &text_lines {
        offsets.push(offset);
        offset += line.len() + 1;
    }
    let mut old_lines: Vec<_> = old.split('\n').collect();
    if old.ends_with('\n') {
        old_lines.pop();
    }
    let trimmed: Vec<_> = text_lines
        .iter()
        .map(|s| s.trim_matches(js_space))
        .collect();
    let pattern: Vec<_> = old_lines.iter().map(|s| s.trim_matches(js_space)).collect();
    let hits = starts(&trimmed, &pattern);
    let mut candidate = None;
    for (i, hit) in hits.iter().enumerate().take(text_lines.len()) {
        if !hit || i + pattern.len() > text_lines.len() {
            continue;
        }
        let last = i + pattern.len() - 1;
        if old.ends_with('\n') && last + 1 == text_lines.len() {
            continue;
        }
        let end = offsets[last] + text_lines[last].len() + usize::from(old.ends_with('\n'));
        consider(source, &mut candidate, offsets[i]..end)?;
    }
    if let Some(span) = candidate {
        return guarded(source, old, span, EditMatchStrategy::LineTrimmed);
    }
    for escape in [false, true] {
        let index = Index::new(source, escape);
        let old_index = Index::new(old, escape);
        let pattern = if escape {
            old_index.text.as_str()
        } else {
            old_index.text.trim_matches(' ')
        };
        let hits = starts(index.text.as_bytes(), pattern.as_bytes());
        let short_hits = if escape && pattern.ends_with('\\') {
            Some(starts(
                index.text.as_bytes(),
                &pattern.as_bytes()[..pattern.len() - 1],
            ))
        } else {
            None
        };
        if escape {
            // The source permits a direct unescaped substring, as well as blocks.
            if let Some(start) = source.find(pattern) {
                consider(source, &mut candidate, start..start + pattern.len())?;
            }
        }
        let count = if escape { lines(pattern) } else { lines(old) };
        if count <= text_lines.len() && !pattern.is_empty() {
            for i in 0..=text_lines.len() - count {
                let last = i + count - 1;
                let end = offsets[last] + text_lines[last].len();
                let (a, b, dangling) = index.window(offsets[i], end, escape);
                let matches = if dangling {
                    short_hits
                        .as_ref()
                        .is_some_and(|hits| b - a + 1 == pattern.len() && hits[a])
                } else {
                    b - a == pattern.len() && hits[a]
                };
                if matches {
                    consider(source, &mut candidate, offsets[i]..end)?;
                }
            }
        }
        if let Some(span) = candidate {
            let strategy = if escape {
                EditMatchStrategy::Escape
            } else {
                EditMatchStrategy::Whitespace
            };
            return guarded(source, old, span, strategy);
        }
    }
    Err(failed("Edit old_string not found"))
}

fn consider(
    source: &str,
    candidate: &mut Option<Range<usize>>,
    span: Range<usize>,
) -> Result<(), ToolError> {
    if span.is_empty() || candidate.as_ref() == Some(&span) {
        return Ok(());
    }
    if candidate.is_some() {
        return Err(failed(
            "Edit fuzzy match has different candidates; provide more exact context",
        ));
    }
    let text = &source[span.clone()];
    let first = source.find(text).expect("candidate is a source span");
    if source.rfind(text) != Some(first) {
        return Err(failed(
            "Edit fuzzy span occurs more than once; provide more exact context",
        ));
    }
    *candidate = Some(first..first + text.len());
    Ok(())
}

fn guarded(
    source: &str,
    old: &str,
    span: Range<usize>,
    strategy: EditMatchStrategy,
) -> Result<(Range<usize>, EditMatchStrategy), ToolError> {
    let matched = &source[span.clone()];
    let old_lines = lines(old);
    if lines(matched) >= (old_lines + 3).max(old_lines * 2)
        || (old_lines > 1
            && trimmed_len(matched) > (trimmed_len(old) + 500).max(trimmed_len(old) * 4))
    {
        return Err(failed(
            "Edit fuzzy matched span is much larger than old_string",
        ));
    }
    Ok((span, strategy))
}
