/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type { ClientLocale } from '@maka-agent/plugin-sdk/client';

const en = {
  title: 'Skills',
  locations: 'Discovery directories',
  refreshLocations: 'Refresh directories',
  createFolder: 'Create and open folder',
  validSkills: 'Valid',
  invalidSkills: 'Invalid',
  locationNames: {
    'project:maka': 'Project · Maka',
    'project:agents': 'Project · Agents',
    'workspace:legacy': 'This Host · Skills',
    'user:maka': 'User · Maka',
    'user:agents': 'User · Agents',
  },
  locationStatuses: {
    available: 'Available',
    missing: 'Not created',
    blocked_path: 'Blocked path',
    read_failed: 'Cannot read',
    unavailable: 'Unavailable',
  },
  available: 'Use a Skill',
  manage: 'Manage',
  import: 'Import source',
  openFile: 'Open file',
  openFolder: 'Open folder',
  installed: 'Installed',
  bundled: 'Bundled',
  sources: 'Local sources',
  refresh: 'Refresh',
  recover: 'Recover user library',
  next: 'Next page',
  add: 'Create starter',
  install: 'Install',
  remove: 'Delete',
  enable: 'Enable',
  disable: 'Disable',
  pin: 'Pin',
  unpin: 'Unpin',
  preview: 'Preview update',
  current: 'Current',
  source: 'Incoming',
  apply: 'Apply this update',
  cancel: 'Cancel',
  confirm: 'Delete this Skill?',
  empty: 'No Skills',
  failed: 'Operation failed. Refresh to retry.',
  changed: 'Sources changed. Refresh before continuing.',
  truncated: 'Preview shortened; the update uses the full files.',
  filter: 'Filter Skills',
};

export const copy = {
  en,
  'zh-CN': {
    title: 'Skills',
    locations: '发现目录',
    refreshLocations: '刷新目录',
    createFolder: '创建并打开目录',
    validSkills: '有效',
    invalidSkills: '无效',
    locationNames: {
      'project:maka': '项目 · Maka',
      'project:agents': '项目 · Agents',
      'workspace:legacy': '此 Host · 技能',
      'user:maka': '用户 · Maka',
      'user:agents': '用户 · Agents',
    },
    locationStatuses: {
      available: '可用',
      missing: '尚未创建',
      blocked_path: '路径不可用',
      read_failed: '无法读取',
      unavailable: '不可用',
    },
    available: '使用技能',
    manage: '管理',
    import: '导入来源',
    openFile: '打开文件',
    openFolder: '打开目录',
    installed: '已安装',
    bundled: '内置来源',
    sources: '本地来源',
    refresh: '刷新',
    recover: '恢复用户技能目录',
    next: '下一页',
    add: '创建入门技能',
    install: '安装',
    remove: '删除',
    enable: '启用',
    disable: '停用',
    pin: '置顶',
    unpin: '取消置顶',
    preview: '预览更新',
    current: '当前内容',
    source: '新内容',
    apply: '应用此更新',
    cancel: '取消',
    confirm: '删除此技能？',
    empty: '没有技能',
    failed: '操作失败，请刷新后重试。',
    changed: '来源已变化，请刷新后继续。',
    truncated: '预览已缩短，更新将使用完整文件。',
    filter: '筛选技能',
  },
  'zh-TW': {
    title: 'Skills',
    locations: '探索目錄',
    refreshLocations: '重新整理目錄',
    createFolder: '建立並開啟目錄',
    validSkills: '有效',
    invalidSkills: '無效',
    locationNames: {
      'project:maka': '專案 · Maka',
      'project:agents': '專案 · Agents',
      'workspace:legacy': '此 Host · 技能',
      'user:maka': '使用者 · Maka',
      'user:agents': '使用者 · Agents',
    },
    locationStatuses: {
      available: '可用',
      missing: '尚未建立',
      blocked_path: '路徑不可用',
      read_failed: '無法讀取',
      unavailable: '不可用',
    },
    available: '使用技能',
    manage: '管理',
    import: '匯入來源',
    openFile: '開啟檔案',
    openFolder: '開啟目錄',
    installed: '已安裝',
    bundled: '內建來源',
    sources: '本機來源',
    refresh: '重新整理',
    recover: '復原使用者技能目錄',
    next: '下一頁',
    add: '建立入門技能',
    install: '安裝',
    remove: '刪除',
    enable: '啟用',
    disable: '停用',
    pin: '置頂',
    unpin: '取消置頂',
    preview: '預覽更新',
    current: '目前內容',
    source: '新內容',
    apply: '套用此更新',
    cancel: '取消',
    confirm: '刪除此技能？',
    empty: '沒有技能',
    failed: '操作失敗，請重新整理後重試。',
    changed: '來源已變更，請重新整理後繼續。',
    truncated: '預覽已縮短，更新將使用完整檔案。',
    filter: '篩選技能',
  },
} satisfies Record<ClientLocale, typeof en>;
export type Copy = typeof en;
